In [6]:
data = {
    'Name': ['John', 'Doe', 'Alice'],
    'Age': [45, 55, 65]
}

In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame(data)

In [9]:
df

    Name  Age
0   John   45
1    Doe   55
2  Alice   65

In [13]:
loc={
    'rollnumber':[60,61,62],
    'age' :[23,24,25],
    'mathsmark' :[19,20,21]
}

In [14]:
lb=pd.DataFrame(loc)

In [15]:
lb

   rollnumber  age  mathsmark
0          60   23         19
1          61   24         20
2          62   25         21